Implemented protection apply and delete commands
g4s8/gitstrap pull request #71
Opened 2021-05-19 21:12 UTC by OrlovM

For #60 - implemented protection apply and delete commands.

Also added pull request review field to protection spec.

2021-05-25 12:15 UTC, OrlovM commented
@g4s8 please review PR!

2021-05-28 09:29 UTC, g4s8 requested changes
@OrlovM please check my comments

2021-05-28 09:29 UTC, g4s8 commented on internal/gitstrap/apply.go
> +		return err
Let's return a bit more information about the error and wrap the "cause" using `%w` format parameter, e.g. `fmt.Errorf("protection name is required: %w", err)`

2021-05-28 09:29 UTC, g4s8 commented on internal/gitstrap/apply.go
> +		return err
And same here

2021-05-28 09:29 UTC, g4s8 commented on internal/gitstrap/delete.go
> +		return err
And here we can add more details to errors

2021-05-28 09:29 UTC, g4s8 commented on internal/spec/protection.go
> +	Checks []string `yaml:"checks,omitempty"`
Documentation comment line should start with the same word as field name (`Checks` in this case) to generate proper documentation

2021-05-28 09:29 UTC, g4s8 commented on internal/spec/protection.go
> +		Teams []string `yaml:"teams,omitempty"`
These fields look not clear -- `Review.Users` is not obvious to understand, I'd change it to `Review.Dismiss.Users` (with a nested struct)

2021-05-28 09:29 UTC, g4s8 commented on internal/spec/protection.go
> +		Stale bool `yaml:"stale,omitempty"`
And this field could be moved to `Dismiss` nested struct too

2021-06-03 19:47 UTC, OrlovM commented
@g4s8 please, review changes.

2021-06-04 06:01 UTC, g4s8 approved these changes
@OrlovM thanks

2021-06-04 06:01 UTC, merged